spring:
  application:
    name: springboot-init-madou
  profiles:
    active: dev
  # swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    # 1天过期
    timeout: 86400
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/gemall
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

    # Redis 配置
    # todo 需替换配置，然后取消注释
  #  redis:
  #    database: 1
  #    host: localhost
  #    port: 6379
  #    timeout: 5000
  #    password: 123456
  # 文件上传


  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  port: 9090
  address: 0.0.0.0
  servlet:
    context-path: /api
    #cookie 1天过期
    session:
      cookie:
        max-age: 86400
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 逻辑删除
      logic-delete-value: 1 # 逻辑删除
      logic-not-delete-value: 0 # 逻辑未删除
express:
  enable: false
  appId: "XXXXXXXXX"
  appKey: "XXXXXXXXXXXXXXXXXXXXXXXXX"
  vendors:
  - code: "ZTO"
    name: "中通快递"
  - code: "YTO"
    name: "圆通速递"
  - code: "YD"
    name: "韵达速递"
  - code: "YZPY"
    name: "邮政快递包裹"
  - code: "EMS"
    name: "EMS"
  - code: "DBL"
    name: "德邦快递"
  - code: "FAST"
    name: "快捷快递"
  - code: "ZJS"
    name: "宅急送"
  - code: "TNT"
    name: "TNT快递"
  - code: "UPS"
    name: "UPS"
  - code: "DHL"
    name: "DHL"
  - code: "FEDEX"
    name: "FEDEX联邦(国内件)"
  - code: "FEDEX_GJ"
    name: "FEDEX联邦(国际件)"
